### PR TITLE
borders same size and perfectly aligned, signup button visible, solid…

### PR DESCRIPTION
**Pull request by Aryanbhargava18**

### CODE REVIEW

**Comment by Aryanbhargava18** [comment]
@yyppsk please assign it to me.

**Review by yyppsk — CHANGES_REQUESTED** [review]
This code modifies the original design of the signup page. Please ensure that the original design is retained and then fix the alignment of the signup and footer.

**Comment by Aryanbhargava18** [comment]
it is same as original design i have just aligned the borders and also made the signup button visible by translating the full box above.

**Comment by yyppsk** [comment]
@Aryanbhargava18 
Original :
image

After Your Code:

image

**Comment by Aryanbhargava18** [comment]
It's UI is now looking more appealing and also sign up button became visible, which couldn't be dine without moving the box up, ping me and say the changes in the original you'd like then.

**Comment by yyppsk** [comment]
> It's UI is now looking more appealing and also sign up button became visible, which couldn't be dine without moving the box up, ping me and say the changes in the original you'd like then.

Try to keep the same design aesthetics but change the positon to fit the signup button.

**Comment by Aryanbhargava18** [comment]
now check @yyppsk

**Comment by yyppsk** [comment]
> now check @yyppsk

It's not completely aligned but still I will merge it.

**Pull request merged**
